# Generated by Django 4.0.4 on 2022-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=40, verbose_name='Direccion')),
                ('country', models.CharField(max_length=40, verbose_name='Pais')),
                ('phone', models.CharField(max_length=40, verbose_name='Anexo')),
            ],
            options={
                'verbose_name_plural': 'Store',
                'db_table': 'store',
                'ordering': ('id',),
            },
        ),
    ]
